language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

  - pip install coveralls

  - pip install pytest-cov

script: 
  - python -m pytest --with-coverage --cover-package=app  && coverage report
  
  - coveralls

after_success:
  - coveralls
